
application: ttc-proximobus
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /examples
  static_dir: examples

- url: /
  static_files: index.html
  upload: index.html

- url: /docs.html
  static_files: documentation.html
  upload: documentation.html

- url: /.*
  script: handle_request.py

